interface Events {
  id: number;
  eve_eventtype_id_fk: number;
  eve_unit_id_fk: number | null;
  eve_oncologycategory_id_fk: number;
  eve_characterizationcase_id_fk: number | null;
  eve_risk_type_id: number | null;
  eve_materialized_adverse_event_id: number | null;
  eve_materialized_incident_id: number | null;
  eve_name: string;
  eve_medicineassociated: boolean;
  eve_deviceassociated: boolean;
  eve_stay: boolean;
  eve_mentalhealth: boolean;
  eve_publichealth: boolean;
  eve_oncologicalpathology: boolean;
  eve_medicines: boolean;
  eve_devices: boolean;
  eve_chemotherapy: boolean;
  eve_cerebral: boolean;
  eve_respiratory: boolean;
  eve_cardiovascular: boolean;
  eve_prostate: boolean;
  eve_renal: boolean;
  eve_gastrointestinal: boolean;
  eve_metabolic: boolean;
  eve_immunological: boolean;
  eve_nutritional: boolean;
  eve_transfusional: boolean;
  eve_changesparaclinical: boolean;
  eve_surgery: boolean;
  eve_procedures: boolean;
  eve_infectious: boolean;
  eve_status: boolean;
  createdAt: string;
  updateAt: string;
  deletedAt: string | null;
  eventType?: EventType;
  caseReportValidate?: CaseReportValidate[];
  unit?: Unit;
  riskType?: RiskType;
  oncologyCategory?: OncologyCategory;
  materializedAdverseEvent?: Events;
  materializedIncident?: Events;
}
