export enum DescriptionOtherEnum {
  DESCRIPTION_EVENT_RISK_OTHER = "RIESGO OTROS",
  DESCRIPTION_EVENT_OTHER = "OTROS",
  DESCRIPTION_DEVICE_TYPE_OTHER = "OTROS",
  DESCRIPTION_DAMAGE_TYPE_OTHER = "OTROS",
  DESCRIPTION_FLUID_TYPE_OTHER = "OTROS",
  DESCRIPTION_FLUID_TYPE_NAME = "LIQUIDOS",
  DESCRIPTION_INFLUENCY_FACTOR_OTHER = "OTROS",
  DESCRIPTION_FAILED_MEASURE_OTHER = "OTROS",
  DESCRIPTION_RISK_FACTOR_OTHER = "OTROS",
}
