export enum ResearchCategoryEnum {
  DEVICE_TYPE = "TIPO DE DISPOSITIVO",
  DAMAGE_TYPE = "TIPO DE DAÑO",
  WHAT_TYPE_OF_FLUID_WAS_BEING_PASSED_THROUGH_THE_DEVICE = "QUE TIPO SE FLUIDO SE ESTABA PASANDO POR EL DISPOSITIVO",
  INDICATE_ONE_OR_SEVERAL_OPTIONS_OF_WHAT_INFLUENCED_THE_PRESENTATION_OF_THE_CASE = "SEÑALE UNA O VARIAS OPCIONES DE LO QUE INFLUYO EN LA PRESENTACION DEL CASO",
  WHAT_PHYSICAL_AND_TECHNOLOGICAL_MEASURES_FAILED = "QUE MEDIDAS FISICAS Y TECNOLOGICAS FALLARON SEÑALE TODO O UNA",
  WHAT_RISK_FACTORS_DID_THE_PATIENT_AND_FAMILY_HAVE = "QUE FACTORES DE RIESGO TENIA EL PACIENTE Y FAMILIA",
  LEVEL_OF_SAFETY_BARRIERS_ESTABLISHED_IN_THE_INSTITUTION_TO_PREVENT_FAILURES = "CONSIDERA USTED QUE LAS BARRERAS DE SEGURIDAD ESTABLECIDAS EN LA INSTITUCIÓN PARA EVITAR FALLOS DE ESTE TIPO SON DE NIVEL",
}
