export enum CaseTypeReportEnum {
  RISK = 'RIESGO',
  ADVERSE_EVENT = 'EVENTO ADVERSO O COMPLICACION',
  INCIDENT = 'INCIDENTE',
  INDICATING_UNSAFE_CARE = 'INDICIO DE ATENCIÓN INSEGURA',
  COMPLICATIONS = 'COMPLICACIONES',
  // agregar un tipo de caso nuevo
}
