export enum ResearchInstrumentEnum {
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_VASCULAR_ACCESS = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS AL ACCESO VASCULAR',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_MEDICATION_OR_FLUIDS = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS A LA MEDICACION O FLUIDOS',
  RESEARCH_INSTRUMENT_FOR_OTHER_CASES = 'INSTRUMENTO DE INVESTIGACION DE OTROS CASOS',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_FALLS = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS A CAIDAS',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_ERROR_IN_DIAGNOSIS_INADEQUATE_APPROACH_OR_STAY = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS A ERROR EN EL DIAGNOSTICO ENFOQUE O ESTANCIA INADECUADO',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_MEDICAL_DEVICES = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS DISPOSITIVOS MEDICOS',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_PERFORMANCE_OF_PROCEDURES = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS REALIZACION DE PROCEDIMIENTOS',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_IDENTIFICATION_FAILURES = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS A FALLAS DE IDENTIFICACION',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_BLOOD_DERIVATIVES = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS  A HEMODERIVADOS',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_SKIN_LESIONS = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS A LESIONES DE PIEL',
  RESEARCH_INSTRUMENT_FOR_CASES_ASSOCIATED_WITH_PNEUMOTHORAX = 'INSTRUMENTO DE INVESTIGACION DE CASOS ASOCIADOS A NEUMOTORAX',
}
